# Generated by Django 5.2.14 on 2026-06-14 19:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fare_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tracking_lat',
            field=models.DecimalField(decimal_places=6, default=Decimal('13.082680'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tracking_lng',
            field=models.DecimalField(decimal_places=6, default=Decimal('80.270721'), max_digits=9),
        ),
    ]
